export const awardImages = [
  {
    id: '1',
    src: require(`../public/awardPhotos/awards1.jpg`),
    text: 'Award 1',
    description: 'Award 1 celebrates exceptional achievements in the field of innovation and creativity. It is presented to individuals and organizations that demonstrate leadership in their respective industries, setting new benchmarks for excellence.',
    numberOfPictures: 15,
    images: [
      require(`../public/awardPhotos/awards1/images.jpeg`),
      require(`../public/awardPhotos/awards1/kis1-2.jpg`),
      require(`../public/awardPhotos/awards1/about-us-Awards-Recognition-2.jpg`),
      require(`../public/awardPhotos/awards1/Award-cup-getty-image (2).jpg`),
      require(`../public/awardPhotos/awards1/about-us-Awards-Recognition-2.jpg`),
      require(`../public/awardPhotos/awards1/Award-cup-getty-image (2).jpg`),
      require(`../public/awardPhotos/awards1/stock-vector-award-ceremony-nomination-name-podium-golden-prize-event-scene-star-ceremony-vector-illustration-2473961179.jpg`),
      require(`../public/awardPhotos/awards1/stock-vector-award-ceremony-nomination-name-podium-golden-prize-event-scene-star-ceremony-vector-illustration-2494638003.jpg`),
    ],
  },
  {
    id: '2',
    src: require(`../public/awardPhotos/awards5.jpg`),
    text: 'Award 5',
    description: 'Award 5 is a prestigious recognition for excellence in various categories, ranging from design to community service. It honors dedication, hard work, and significant contributions to society.',
    numberOfPictures: 15,
    images: [
      require(`../public/awardPhotos/awards1/about-us-Awards-Recognition-2.jpg`),
      require(`../public/awardPhotos/awards1/Award-cup-getty-image (2).jpg`),
      require(`../public/awardPhotos/awards1/images.jpeg`),
      require(`../public/awardPhotos/awards1/kis1-2.jpg`),
      require(`../public/awardPhotos/awards1/stock-vector-award-ceremony-nomination-name-podium-golden-prize-event-scene-star-ceremony-vector-illustration-2473961179.jpg`),
      require(`../public/awardPhotos/awards1/stock-vector-award-ceremony-nomination-name-podium-golden-prize-event-scene-star-ceremony-vector-illustration-2494638003.jpg`),
    ],
  },
  {
    id: '3',
    src: require(`../public/awardPhotos/awards2.png`),
    text: 'Award 2',
    description: 'Award 2 recognizes outstanding contributions in the fields of education and research. It is awarded to professionals whose work has positively impacted their field and made a difference globally.',
    numberOfPictures: 15,
    images: [
      require(`../public/awardPhotos/awards1/about-us-Awards-Recognition-2.jpg`),
      require(`../public/awardPhotos/awards1/Award-cup-getty-image (2).jpg`),
      require(`../public/awardPhotos/awards1/about-us-Awards-Recognition-2.jpg`),
      require(`../public/awardPhotos/awards1/Award-cup-getty-image (2).jpg`),
      require(`../public/awardPhotos/awards1/images.jpeg`),
      require(`../public/awardPhotos/awards1/kis1-2.jpg`),
    ],
  },
  {
    id: '4',
    src: require(`../public/awardPhotos/awards3.jpg`),
    text: 'Award 3',
    description: 'Award 3 is dedicated to those who excel in the realm of environmental sustainability. It highlights initiatives that promote eco-friendly practices and sustainable development.',
    numberOfPictures: 15,
    images: [
      require(`../public/awardPhotos/awards1/about-us-Awards-Recognition-2.jpg`),
      require(`../public/awardPhotos/awards1/stock-vector-award-ceremony-nomination-name-podium-golden-prize-event-scene-star-ceremony-vector-illustration-2473961179.jpg`),
      require(`../public/awardPhotos/awards1/stock-vector-award-ceremony-nomination-name-podium-golden-prize-event-scene-star-ceremony-vector-illustration-2494638003.jpg`),
    ],
  },
  {
    id: '5',
    src: require(`../public/awardPhotos/awards5.jpg`),
    text: 'Award 5',
    description: 'Award 5 celebrates individuals and teams who have made groundbreaking advancements in technology and innovation. It is a symbol of ingenuity, creativity, and technical prowess.',
    numberOfPictures: 15,
    images: [
      require(`../public/awardPhotos/awards1/about-us-Awards-Recognition-2.jpg`),
      require(`../public/awardPhotos/awards1/Award-cup-getty-image (2).jpg`),
      require(`../public/awardPhotos/awards1/images.jpeg`),
      require(`../public/awardPhotos/awards1/kis1-2.jpg`),
    ],
  },
  {
    id: '6',
    src: require(`../public/awardPhotos/awards4.jpg`),
    text: 'Award 4',
    description: 'Award 4 honors humanitarian efforts, acknowledging individuals and groups that have made a significant impact in philanthropy and social welfare. It is presented to those who strive for positive societal change.',
    numberOfPictures: 15,
    images: [
      require(`../public/awardPhotos/awards1/about-us-Awards-Recognition-2.jpg`),
      require(`../public/awardPhotos/awards1/Award-cup-getty-image (2).jpg`),
    ],
  },
  {
    id: '7',
    src: require(`../public/awardPhotos/awards2.png`),
    text: 'Award 2',
    description: 'Award 2 recognizes excellence in arts and culture, celebrating creatives who have significantly contributed to the enrichment of cultural heritage. It highlights achievements in various forms of artistic expression.',
    numberOfPictures: 15,
    images: [
      require(`../public/awardPhotos/awards1/about-us-Awards-Recognition-2.jpg`),
      require(`../public/awardPhotos/awards1/Award-cup-getty-image (2).jpg`),
      require(`../public/awardPhotos/awards1/images.jpeg`),
      require(`../public/awardPhotos/awards1/kis1-2.jpg`),
    ],
  },
  {
    id: '8',
    src: require(`../public/awardPhotos/awards5.jpg`),
    text: 'Award 5',
    description: 'Award 5 is presented to companies and organizations for leadership in business and commerce. It symbolizes success in implementing cutting-edge strategies and achieving unparalleled growth in the market.',
    numberOfPictures: 15,
    images: [
      require(`../public/awardPhotos/awards1/about-us-Awards-Recognition-2.jpg`),
      require(`../public/awardPhotos/awards1/Award-cup-getty-image (2).jpg`),
    ],
  },
];
