export const galleryImages = [
  {
    id: '1',
    src: require(`../../public/galleryImages/Rectangle 235.jpg`),
    title: 'Gallery 1',
    description: 'A collection of stunning landscapes from various regions of the world.',
    numberOfPictures: 8,
    images: [
      require(`../../public/galleryImages/Rectangle 235.jpg`),
      require(`../../public/galleryImages/Rectangle 236.jpg`),
      require(`../../public/galleryImages/Rectangle 237.jpg`),
      require(`../../public/galleryImages/Rectangle 238.jpg`),
      require(`../../public/galleryImages/Rectangle 239.jpg`),
      require(`../../public/galleryImages/Rectangle 240.jpg`),
      require(`../../public/galleryImages/Rectangle 241.jpg`),
      require(`../../public/galleryImages/Rectangle 242.jpg`),
    ],
  },
  {
    id: '2',
    src: require(`../../public/galleryImages/Rectangle 236.jpg`),
    title: 'Gallery 2',
    description: 'A series of abstract compositions with bold colors and shapes.',
    numberOfPictures: 7,
    images: [
      require(`../../public/galleryImages/Rectangle 236.jpg`),
      require(`../../public/galleryImages/Rectangle 237.jpg`),
      require(`../../public/galleryImages/Rectangle 241.jpg`),
      require(`../../public/galleryImages/Rectangle 243.jpg`),
      require(`../../public/galleryImages/Rectangle 244.jpg`),
      require(`../../public/galleryImages/Rectangle 245.jpg`),
      require(`../../public/galleryImages/Rectangle 246.jpg`),
    ],
  },
  {
    id: '3',
    src: require(`../../public/galleryImages/Rectangle 237.jpg`),
    title: 'Gallery 3',
    description: 'An urban exploration of cityscapes and human environments.',
    numberOfPictures: 9,
    images: [
      require(`../../public/galleryImages/Rectangle 237.jpg`),
      require(`../../public/galleryImages/Rectangle 239.jpg`),
      require(`../../public/galleryImages/Rectangle 240.jpg`),
      require(`../../public/galleryImages/Rectangle 241.jpg`),
      require(`../../public/galleryImages/Rectangle 242.jpg`),
      require(`../../public/galleryImages/Rectangle 246.jpg`),
      require(`../../public/galleryImages/Rectangle 248.jpg`),
      require(`../../public/galleryImages/Rectangle 249.jpg`),
      require(`../../public/galleryImages/Rectangle 250.jpg`),
    ],
  },
  {
    id: '4',
    src: require(`../../public/galleryImages/Rectangle 238.jpg`),
    title: 'Gallery 4',
    description: 'A closer look at the elements of nature, from flora to fauna.',
    numberOfPictures: 6,
    images: [
      require(`../../public/galleryImages/Rectangle 238.jpg`),
      require(`../../public/galleryImages/Rectangle 240.jpg`),
      require(`../../public/galleryImages/Rectangle 244.jpg`),
      require(`../../public/galleryImages/Rectangle 246.jpg`),
      require(`../../public/galleryImages/Rectangle 248.jpg`),
      require(`../../public/galleryImages/Rectangle 249.jpg`),
    ],
  },
  {
    id: '5',
    src: require(`../../public/galleryImages/Rectangle 239.jpg`),
    title: 'Gallery 5',
    description: 'Photographs that depict the serenity of rural landscapes.',
    numberOfPictures: 7,
    images: [
      require(`../../public/galleryImages/Rectangle 239.jpg`),
      require(`../../public/galleryImages/Rectangle 241.jpg`),
      require(`../../public/galleryImages/Rectangle 242.jpg`),
      require(`../../public/galleryImages/Rectangle 243.jpg`),
      require(`../../public/galleryImages/Rectangle 245.jpg`),
      require(`../../public/galleryImages/Rectangle 247.jpg`),
      require(`../../public/galleryImages/Rectangle 248.jpg`),
    ],
  },
  {
    id: '6',
    src: require(`../../public/galleryImages/Rectangle 240.jpg`),
    title: 'Gallery 6',
    description: 'Abstract and surreal images that challenge the viewer’s perception.',
    numberOfPictures: 8,
    images: [
      require(`../../public/galleryImages/Rectangle 240.jpg`),
      require(`../../public/galleryImages/Rectangle 243.jpg`),
      require(`../../public/galleryImages/Rectangle 245.jpg`),
      require(`../../public/galleryImages/Rectangle 247.jpg`),
      require(`../../public/galleryImages/Rectangle 249.jpg`),
      require(`../../public/galleryImages/Rectangle 251.jpg`),
      require(`../../public/galleryImages/Rectangle 252.jpg`),
      require(`../../public/galleryImages/Rectangle 253.jpg`),
    ],
  },
  {
    id: '7',
    src: require(`../../public/galleryImages/Rectangle 241.jpg`),
    title: 'Gallery 7',
    description: 'Bright and bold images that celebrate modern design and minimalism.',
    numberOfPictures: 6,
    images: [
      require(`../../public/galleryImages/Rectangle 241.jpg`),
      require(`../../public/galleryImages/Rectangle 243.jpg`),
      require(`../../public/galleryImages/Rectangle 244.jpg`),
      require(`../../public/galleryImages/Rectangle 246.jpg`),
      require(`../../public/galleryImages/Rectangle 249.jpg`),
      require(`../../public/galleryImages/Rectangle 251.jpg`),
    ],
  },
  {
    id: '8',
    src: require(`../../public/galleryImages/Rectangle 242.jpg`),
    title: 'Gallery 8',
    description: 'Dynamic and energetic images that capture movement and life.',
    numberOfPictures: 8,
    images: [
      require(`../../public/galleryImages/Rectangle 242.jpg`),
      require(`../../public/galleryImages/Rectangle 243.jpg`),
      require(`../../public/galleryImages/Rectangle 245.jpg`),
      require(`../../public/galleryImages/Rectangle 246.jpg`),
      require(`../../public/galleryImages/Rectangle 250.jpg`),
      require(`../../public/galleryImages/Rectangle 251.jpg`),
      require(`../../public/galleryImages/Rectangle 252.jpg`),
      require(`../../public/galleryImages/Rectangle 253.jpg`),
    ],
  },
  {
    id: '9',
    src: require(`../../public/galleryImages/Rectangle 243.jpg`),
    title: 'Gallery 9',
    description: 'Artistic portraits focusing on the human experience.',
    numberOfPictures: 7,
    images: [
      require(`../../public/galleryImages/Rectangle 243.jpg`),
      require(`../../public/galleryImages/Rectangle 244.jpg`),
      require(`../../public/galleryImages/Rectangle 247.jpg`),
      require(`../../public/galleryImages/Rectangle 249.jpg`),
      require(`../../public/galleryImages/Rectangle 250.jpg`),
      require(`../../public/galleryImages/Rectangle 252.jpg`),
      require(`../../public/galleryImages/Rectangle 253.jpg`),
    ],
  },
  {
    id: '10',
    src: require(`../../public/galleryImages/Rectangle 244.jpg`),
    title: 'Gallery 10',
    description: 'Visual stories captured through a minimalist lens.',
    numberOfPictures: 9,
    images: [
      require(`../../public/galleryImages/Rectangle 244.jpg`),
      require(`../../public/galleryImages/Rectangle 246.jpg`),
      require(`../../public/galleryImages/Rectangle 248.jpg`),
      require(`../../public/galleryImages/Rectangle 250.jpg`),
      require(`../../public/galleryImages/Rectangle 251.jpg`),
      require(`../../public/galleryImages/Rectangle 252.jpg`),
      require(`../../public/galleryImages/Rectangle 253.jpg`),
      require(`../../public/galleryImages/Rectangle 247.jpg`),
      require(`../../public/galleryImages/Rectangle 262.jpg`),
    ],
  },
  {
    id: '11',
    src: require(`../../public/galleryImages/Rectangle 245.jpg`),
    title: 'Gallery 11',
    description: 'A series of dramatic stills from iconic scenes in nature.',
    numberOfPictures: 6,
    images: [
      require(`../../public/galleryImages/Rectangle 245.jpg`),
      require(`../../public/galleryImages/Rectangle 247.jpg`),
      require(`../../public/galleryImages/Rectangle 250.jpg`),
      require(`../../public/galleryImages/Rectangle 252.jpg`),
      require(`../../public/galleryImages/Rectangle 253.jpg`),
      require(`../../public/galleryImages/Rectangle 262.jpg`),
    ],
  },
  {
    id: '12',
    src: require(`../../public/galleryImages/Rectangle 246.jpg`),
    title: 'Gallery 12',
    description: 'Landscapes that exhibit the beauty of untouched natural spaces.',
    numberOfPictures: 7,
    images: [
      require(`../../public/galleryImages/Rectangle 246.jpg`),
      require(`../../public/galleryImages/Rectangle 248.jpg`),
      require(`../../public/galleryImages/Rectangle 250.jpg`),
      require(`../../public/galleryImages/Rectangle 251.jpg`),
      require(`../../public/galleryImages/Rectangle 253.jpg`),
      require(`../../public/galleryImages/Rectangle 261.jpg`),
      require(`../../public/galleryImages/Rectangle 262.jpg`),
    ],
  },
  {
    id: '13',
    src: require(`../../public/galleryImages/Rectangle 247.jpg`),
    title: 'Gallery 13',
    description: 'Black and white photography series focusing on contrast and texture.',
    numberOfPictures: 8,
    images: [
      require(`../../public/galleryImages/Rectangle 247.jpg`),
      require(`../../public/galleryImages/Rectangle 249.jpg`),
      require(`../../public/galleryImages/Rectangle 250.jpg`),
      require(`../../public/galleryImages/Rectangle 251.jpg`),
      require(`../../public/galleryImages/Rectangle 252.jpg`),
      require(`../../public/galleryImages/Rectangle 253.jpg`),
      require(`../../public/galleryImages/Rectangle 261.jpg`),
      require(`../../public/galleryImages/Rectangle 262.jpg`),
    ],
  },
  {
    id: '14',
    src: require(`../../public/galleryImages/Rectangle 248.jpg`),
    title: 'Gallery 14',
    description: 'Bold imagery that captures the vibrancy of modern architecture.',
    numberOfPictures: 6,
    images: [
      require(`../../public/galleryImages/Rectangle 248.jpg`),
      require(`../../public/galleryImages/Rectangle 250.jpg`),
      require(`../../public/galleryImages/Rectangle 251.jpg`),
      require(`../../public/galleryImages/Rectangle 252.jpg`),
      require(`../../public/galleryImages/Rectangle 253.jpg`),
      require(`../../public/galleryImages/Rectangle 261.jpg`),
    ],
  },
  {
    id: '15',
    src: require(`../../public/galleryImages/Rectangle 249.jpg`),
    title: 'Gallery 15',
    description: 'A mixture of vintage and modern cityscapes from across the globe.',
    numberOfPictures: 9,
    images: [
      require(`../../public/galleryImages/Rectangle 249.jpg`),
      require(`../../public/galleryImages/Rectangle 250.jpg`),
      require(`../../public/galleryImages/Rectangle 251.jpg`),
      require(`../../public/galleryImages/Rectangle 252.jpg`),
      require(`../../public/galleryImages/Rectangle 253.jpg`),
      require(`../../public/galleryImages/Rectangle 261.jpg`),
      require(`../../public/galleryImages/Rectangle 262.jpg`),
      require(`../../public/galleryImages/Rectangle 244.jpg`),
      require(`../../public/galleryImages/Rectangle 262.jpg`),
    ],
  },
  {
    id: '16',
    src: require(`../../public/galleryImages/Rectangle 250.jpg`),
    title: 'Gallery 16',
    description: 'Urban jungle: a celebration of street life and culture.',
    numberOfPictures: 7,
    images: [
      require(`../../public/galleryImages/Rectangle 250.jpg`),
      require(`../../public/galleryImages/Rectangle 251.jpg`),
      require(`../../public/galleryImages/Rectangle 252.jpg`),
      require(`../../public/galleryImages/Rectangle 253.jpg`),
      require(`../../public/galleryImages/Rectangle 261.jpg`),
      require(`../../public/galleryImages/Rectangle 262.jpg`),
      require(`../../public/galleryImages/Rectangle 246.jpg`),
    ],
  },
  {
    id: '17',
    src: require(`../../public/galleryImages/Rectangle 251.jpg`),
    title: 'Gallery 17',
    description: 'An eclectic mix of old and new: urban landscapes transformed by modern architecture.',
    numberOfPictures: 6,
    images: [
      require(`../../public/galleryImages/Rectangle 251.jpg`),
      require(`../../public/galleryImages/Rectangle 252.jpg`),
      require(`../../public/galleryImages/Rectangle 253.jpg`),
      require(`../../public/galleryImages/Rectangle 261.jpg`),
      require(`../../public/galleryImages/Rectangle 262.jpg`),
      require(`../../public/galleryImages/Rectangle 244.jpg`),
    ],
  },
  {
    id: '18',
    src: require(`../../public/galleryImages/Rectangle 252.jpg`),
    title: 'Gallery 18',
    description: 'Exploring different textures and forms through architectural elements.',
    numberOfPictures: 8,
    images: [
      require(`../../public/galleryImages/Rectangle 252.jpg`),
      require(`../../public/galleryImages/Rectangle 253.jpg`),
      require(`../../public/galleryImages/Rectangle 261.jpg`),
      require(`../../public/galleryImages/Rectangle 262.jpg`),
      require(`../../public/galleryImages/Rectangle 246.jpg`),
      require(`../../public/galleryImages/Rectangle 249.jpg`),
      require(`../../public/galleryImages/Rectangle 248.jpg`),
      require(`../../public/galleryImages/Rectangle 244.jpg`),
    ],
  },
  {
    id: '19',
    src: require(`../../public/galleryImages/Rectangle 253.jpg`),
    title: 'Gallery 19',
    description: 'An exploration of symmetry and balance through city photography.',
    numberOfPictures: 9,
    images: [
      require(`../../public/galleryImages/Rectangle 253.jpg`),
      require(`../../public/galleryImages/Rectangle 261.jpg`),
      require(`../../public/galleryImages/Rectangle 262.jpg`),
      require(`../../public/galleryImages/Rectangle 246.jpg`),
      require(`../../public/galleryImages/Rectangle 249.jpg`),
      require(`../../public/galleryImages/Rectangle 247.jpg`),
      require(`../../public/galleryImages/Rectangle 252.jpg`),
      require(`../../public/galleryImages/Rectangle 250.jpg`),
      require(`../../public/galleryImages/Rectangle 244.jpg`),
    ],
  },
  {
    id: '20',
    src: require(`../../public/galleryImages/Rectangle 262.jpg`),
    title: 'Gallery 20',
    description: 'Cityscapes from dusk to dawn, capturing the life in urban settings.',
    numberOfPictures: 8,
    images: [
      require(`../../public/galleryImages/Rectangle 262.jpg`),
      require(`../../public/galleryImages/Rectangle 261.jpg`),
      require(`../../public/galleryImages/Rectangle 253.jpg`),
      require(`../../public/galleryImages/Rectangle 252.jpg`),
      require(`../../public/galleryImages/Rectangle 251.jpg`),
      require(`../../public/galleryImages/Rectangle 250.jpg`),
      require(`../../public/galleryImages/Rectangle 249.jpg`),
      require(`../../public/galleryImages/Rectangle 244.jpg`),
    ],
  },
];

export default galleryImages;
